package io.github.jacoblasky.recipedump.graph;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonPrimitive;
import java.util.Map;

/**
 * Compares a Java result against a fixture generated by the python oracle -- STRUCTURALLY.
 *
 * <h2>NEVER COMPARE FIXTURE JSON AS TEXT. A THIRD OF EVERY DOUBLE FORMATS DIFFERENTLY.</h2>
 *
 * Measured on 6,012 doubles -- the cost model's own band constants, ratios, and random bit
 * patterns -- with the exact 64-bit patterns written once and formatted by each language:
 *
 * <pre>
 *   python repr()  vs  java Double.toString()
 *     values compared        6012
 *     DIFFERENT STRINGS      1966   (33%)
 *     DIFFERENT VALUES          0
 * </pre>
 *
 * Identical on `eclipse-temurin:8-jdk` and `:25-jdk`, so it is not a JDK-version artefact.
 * The differences are pure notation and they are everywhere:
 *
 * <pre>
 *   py=1e-09                    java=1.0E-9
 *   py=5.2985852125019304e+159  java=5.2985852125019304E159
 *   py=-1.0781342458047461e-122 java=-1.0781342458047461E-122
 * </pre>
 *
 * So {@code assertEquals(expectedJson, actualJson)} would fail on a third of every cost table
 * while both sides are bit-for-bit correct, and the failure would read as a NUMERICAL BUG IN
 * THE PORT. That is the worst possible false positive here: it points at arithmetic that is
 * perfect and sends the reader looking for a rounding error that does not exist.
 *
 * <h2>Numbers compare with exact {@code ==}, never an epsilon</h2>
 *
 * The good news buried in that measurement is 0 value-differing out of 6,012: IEEE 754
 * binary64 is binary64 in both languages, so EXACT reproduction of the cost model is
 * achievable and is the thing worth asserting. An epsilon would hide real drift -- the whole
 * point of a golden fixture is that the arithmetic reproduces exactly. DO NOT add a
 * tolerance parameter to this class; if a comparison needs one, the port has a defect that
 * the tolerance would conceal.
 *
 * <h2>Two conditions the ported code must hold up</h2>
 *
 * <ul>
 * <li>Keep arithmetic in {@code double}, never {@code float}.</li>
 * <li>Preserve operation ORDER. {@code a+b+c} and {@code a+c+b} are not the same double, so
 *     where python folds over a collection, fold over the same collection in the same order.
 *     That is the same insertion-order constraint {@link RecipeGraph} documents, with a
 *     second reason behind it.</li>
 * </ul>
 *
 * Marking the cost classes {@code strictfp} is worth doing when they arrive: on x86-64 it is
 * almost certainly a no-op because the JVM uses SSE2, but Java 8 predates the change that
 * made all floating point strict, and the keyword costs nothing and states the intent.
 * Nothing in this package does floating-point arithmetic yet, so there is nowhere to put it.
 */
public final class JsonFixtures {

    private JsonFixtures() {
    }

    /**
     * Throws with a JSON path naming the first difference, or returns quietly.
     *
     * A path rather than a diff of two documents, because a fixture is thousands of lines and
     * "they differ" is not a finding. `$.tree.children[2].qty` is.
     */
    public static void assertEquivalent(String expectedJson, String actualJson) {
        JsonElement expected = new JsonParser().parse(expectedJson);
        JsonElement actual = new JsonParser().parse(actualJson);
        compare("$", expected, actual);
    }

    public static void assertEquivalent(JsonElement expected, JsonElement actual) {
        compare("$", expected, actual);
    }

    private static void compare(String path, JsonElement expected, JsonElement actual) {
        if (expected.isJsonNull() || actual.isJsonNull()) {
            if (!expected.isJsonNull() || !actual.isJsonNull()) {
                fail(path, expected, actual);
            }
            return;
        }
        if (expected.isJsonPrimitive() && actual.isJsonPrimitive()) {
            comparePrimitive(path, expected.getAsJsonPrimitive(), actual.getAsJsonPrimitive());
            return;
        }
        if (expected.isJsonArray() && actual.isJsonArray()) {
            JsonArray expectedArray = expected.getAsJsonArray();
            JsonArray actualArray = actual.getAsJsonArray();
            if (expectedArray.size() != actualArray.size()) {
                throw new AssertionError(path + ": expected " + expectedArray.size()
                        + " elements, got " + actualArray.size());
            }
            // BY POSITION, never as a bag. Array order is part of the contract the fixture
            // freezes -- see RecipeGraph's iteration-order section and #129.
            for (int i = 0; i < expectedArray.size(); i++) {
                compare(path + "[" + i + "]", expectedArray.get(i), actualArray.get(i));
            }
            return;
        }
        if (expected.isJsonObject() && actual.isJsonObject()) {
            JsonObject expectedObject = expected.getAsJsonObject();
            JsonObject actualObject = actual.getAsJsonObject();
            for (Map.Entry<String, JsonElement> entry : expectedObject.entrySet()) {
                if (!actualObject.has(entry.getKey())) {
                    throw new AssertionError(path + ": missing key " + entry.getKey());
                }
                compare(path + "." + entry.getKey(), entry.getValue(),
                        actualObject.get(entry.getKey()));
            }
            for (Map.Entry<String, JsonElement> entry : actualObject.entrySet()) {
                if (!expectedObject.has(entry.getKey())) {
                    throw new AssertionError(path + ": unexpected key " + entry.getKey());
                }
            }
            // Object KEY order is deliberately not compared: `json.dump(sort_keys=True)` and
            // gson disagree about it, neither python nor java promises it through a parse,
            // and no consumer reads a plan by field position. Array order is the one that
            // carries meaning.
            return;
        }
        fail(path, expected, actual);
    }

    private static void comparePrimitive(String path, JsonPrimitive expected,
                                         JsonPrimitive actual) {
        if (expected.isNumber() && actual.isNumber()) {
            double left = expected.getAsDouble();
            double right = actual.getAsDouble();
            // `Double.compare`, not `==`, so two NaNs match and +0.0 does not silently equal
            // -0.0. Still exact: no tolerance anywhere.
            if (Double.compare(left, right) != 0) {
                throw new AssertionError(path + ": expected " + expected.getAsString()
                        + ", got " + actual.getAsString() + " (bits "
                        + Long.toHexString(Double.doubleToLongBits(left)) + " vs "
                        + Long.toHexString(Double.doubleToLongBits(right)) + ")");
            }
            return;
        }
        if (expected.isBoolean() && actual.isBoolean()) {
            if (expected.getAsBoolean() != actual.getAsBoolean()) {
                fail(path, expected, actual);
            }
            return;
        }
        if (expected.isString() && actual.isString()) {
            if (!expected.getAsString().equals(actual.getAsString())) {
                fail(path, expected, actual);
            }
            return;
        }
        fail(path, expected, actual);
    }

    private static void fail(String path, JsonElement expected, JsonElement actual) {
        throw new AssertionError(path + ": expected " + expected + ", got " + actual);
    }
}
